### ISSUE TITLE
Tag Minor Release

### ISSUE THREAD

**Issue by ymakhloufi** [j13k/yaml-lint#26]
Hi there,

Could you tag a minor release with the 'name' field fix? Or just the latest master-commit? The latest tagged version is currently breaking builds in CI pipelines, unfortunately.

/ Yassin

**Comment by j13k** [comment]
Hi @ymakhloufi, apologies for the delayed response—I've been on a break (it's summer in my part of the world).

I'll endeavour to prep and tag a release shortly, but in the meantime, there is a branch alias, so you can install `master` with `1.1.x-dev`.

**Comment by ymakhloufi** [comment]
Hi @j13k ,
Thanks, that would be great. Since you merged the PR already into master, we currently are referencing a hard-coded commit on it, which works fine-ish. But it would of course be nice to have a tagged version, so we're gonna wait until there's a version 1.1.4

**Comment by j13k** [comment]
Hi @ymakhloufi,

Version 1.1.4 has been released.

Apologies fo the delay—I wanted to squeeze some more work into this release, but finally figured it was worth releasing as is.

Hope it helps—let me know if any problems come up.
