### ISSUE TITLE
Missing GPG signature for PHAR file

### ISSUE THREAD

**Issue by lukaszuznanski** [j13k/yaml-lint#29]
Hi,

maybe we could add GPG signature to PHAR file in releases in order to make your PHAR file installable via `phive` tool.

Here is guide https://phar.io/howto/sign-and-upload-to-github.html

**Comment by j13k** [comment]
Thanks for reporting this—I'll look into it shortly.

**Comment by j13k** [comment]
Hi @lukaszuznanski,

I've just released 1.1.4 and created a new PHAR with signature—they're available from the [release page](https://github.com/j13k/yaml-lint/releases/tag/1.1.4).

Let me know if there are any problems.
