### ISSUE TITLE
Erroring on files missing trailing newline shouldn't fail linting

### ISSUE THREAD

**Issue by davereid-pfg** [j13k/yaml-lint#48]
We use this project to review YAML files and the intent is that linting should prevent any errors from malformed files, but we often get some errors on different sites when YAML files do not contain a trailing empty line, which isn't malformed. Can we separate out this error to a "strict" mode instead or maybe disable this check?

**Comment by j13k** [comment]
It's interesting that an error is raised by the [symfony/yaml](https://github.com/symfony/yaml) parser used in the linter, but not by the YAML parser in your projects. Are you using a different parser in your projects?

In any case, given that the heavy lifting of the YAML parsing is actually performed by the [symfony/yaml](https://github.com/symfony/yaml) component, this issue may be better raised in the upstream project.

If you can demonstrate that the absence of a trailing newline is indeed valid, that project's maintainers might update the parsing logic.
