### ISSUE TITLE
phive installation fails due to a missing gpg key

### ISSUE THREAD

**Issue by jakzal** [j13k/yaml-lint#57]
```
$ phive --no-progress install  j13k/yaml-lint

Phive 0.15.2 - Copyright (C) 2015-2023 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/rate_limit
Downloading https://github.com/j13k/yaml-lint/releases/download/1.1.5/yaml-lint.phar
Downloading https://github.com/j13k/yaml-lint/releases/download/1.1.5/yaml-lint.phar.asc
Downloading key 985E1E22802973B2
Trying to connect to keys.openpgp.org (37.218.245.50)
Downloading https://keys.openpgp.org/pks/lookup?op=get&options=mr&search=0x985E1E22802973B2
Successfully downloaded key.
[WARNING] Parsing key data failed with error code 0: No UIDs in key found
Trying to connect to keyserver.ubuntu.com (162.213.33.9)
Downloading https://keyserver.ubuntu.com/pks/lookup?op=get&options=mr&search=0x985E1E22802973B2
Trying to connect to keyserver.ubuntu.com (162.213.33.8)
Downloading https://keyserver.ubuntu.com/pks/lookup?op=get&options=mr&search=0x985E1E22802973B2
[WARNING] Failed with error code 404: Key not found on keyserver
Trying to connect to pgp.mit.edu (18.9.60.141)
```

re #29

**Comment by j13k** [comment]
Hi @jakzal, thanks for flagging this. The key should now also be on the Ubuntu and MIT key servers. I've tested with a fresh phive install and it grabs the key correctly.

**Comment by jakzal** [comment]
I can confirm it now [works](https://github.com/jakzal/toolbox/actions/runs/4860998810/jobs/8665533604#step:5:286). Thanks 👍 

There's a warning raised, but I have no clue if that's important:

```
Warning:  Parsing key data failed with error code 0: No UIDs in key found
```


<img width="1040" alt="image" src="https://user-images.githubusercontent.com/190447/235663943-149a1170-6f01-44eb-9c21-0f12523196ec.png">

**Comment by j13k** [comment]
Thanks for confirming @jakzal.

Re:

> There's a warning raised, but I have no clue if that's important:
> 
> ```
> Warning:  Parsing key data failed with error code 0: No UIDs in key found
> ```

This is likely because of the issue mentioned in this note from https://phar.io/howto/uploading-public-keys.html:

> Important: keys.openpgp.org strips the UID from the key until ownership is confirmed. The key is useless when no UID is included so make sure you follow the instructions sent to you by openpgp.org.

Unfortunately I used my GitHub `noreply` email to create the key this time, so didn't receive the instruction email sent by the key server.

The other key servers don't seem to have such a requirement, so the phive install still works when it falls back to them.

I will make a point of using a 'real' email when generating the next key.
