### ISSUE TITLE
Offer `--fix` flag to fix formatting errors

### ISSUE THREAD

**Issue by danielbachhuber** [j13k/yaml-lint#81]
`phpcbf` is pretty handy for easily fixing formatting errors. It would be nice if this linter offered something similar!

**Comment by j13k** [comment]
Thanks for the suggestion @danielbachhuber. It does sound like it would be a useful suggestion, however it's beyond the scope of this project.

The yaml-lint tool is intended to be a lightweight wrapper around the parsing logic of the symfony/yaml component, so adding a feature like this would expand the scope significantly.

If the upstream component adds a "fix" feature, we could look at supporting it, but I'll close this request in the meantime.
